### PR TITLE
Remove squash & wash 'feature'

### PR DESCRIPTION
**Pull request by ldir-EDB0**
Washing was mentioned again as a mis-feature.  Let's get rid of it then.

### CODE REVIEW

**Comment by dtaht** [comment]
I still think squashing is very important.

**Comment by ldir-EDB0** [comment]
On 01/06/16 11:05, Dave Täht wrote:

> I still think squashing is very important.

So you want to be able to clear the DSCP bits on outgoing of the qdisc?

**Comment by chromi** [comment]
> On 01/06/16 11:05, Dave Täht wrote:
> 
> > I still think squashing is very important.
> 
> So you want to be able to clear the DSCP bits on outgoing of the qdisc?

Cake can be configured to ignore the DSCP using the “besteffort” flag, which isn’t going away.  This is entirely sufficient for most configurations.

The DSCP can be cleared or rewritten using iptables rules or the DSMARK qdisc/filter.  Honestly, I haven’t figured out how to use the latter in practice - it’s a bit obtuse, like most of the older classful qdiscs - but it does already exist in the mainline kernel, and shouldn’t be too difficult to configure for the basic “clearing” job.

The squash/wash flags in Cake can _only_ clear the DSCP, not rewrite it to a new spec.  This is only useful to work around equipment which misinterprets DSCPs and applies unhelpful PHBs as a result.  Anything more complex and useful would require a full-fledged configuration API, which Cake can’t reasonably keep to itself, and is better done as a separate qdisc (replacing DSMARK, perhaps).

I’ve made it clear for a while that I wanted the feature to go.  I only left it in for so long because it wasn’t absolutely clear at the time that a reasonable high-performance alternative existed, and the cost was minimal.  But DSMARK should be fast enough, so I’m now recommending that as the high-performance replacement, and iptables for “easy mode”.
- Jonathan Morton

**Comment by ldir-EDB0** [comment]
Thank you :-)

**Comment by dtaht** [comment]
On 6/1/16 6:30 AM, chromi wrote:

> > On 01/06/16 11:05, Dave Täht wrote:
> > 
> > > I still think squashing is very important.
> > 
> > So you want to be able to clear the DSCP bits on outgoing of the qdisc?
> 
> Cake can be configured to ignore the DSCP using the “besteffort” flag,
> which isn’t going away. This is entirely sufficient for most configurations.
> 
> The DSCP can be cleared or rewritten using iptables rules or the DSMARK
> qdisc/filter. Honestly, I haven’t figured out how to use the latter in
> practice - it’s a bit obtuse, like most of the older classful qdiscs -
> but it does already exist in the mainline kernel, and shouldn’t be too
> difficult to configure for the basic “clearing” job.
> 
> The squash/wash flags in Cake can _only_ clear the DSCP, not rewrite it
> to a new spec. This is only useful to work around equipment which
> misinterprets DSCPs and applies unhelpful PHBs as a result. Anything
> more complex and useful would require a full-fledged configuration API,
> which Cake can’t reasonably keep to itself, and is better done as a
> separate qdisc (replacing DSMARK, perhaps).

The point being that the damn tos bits should be cleared on ingress to
avoid confusing other stuff inside your own dmark. Right now, nearly all
traffic on my principal use case (comcast) gets marked as background.
This means that much traffic hits the wifi - and ends up in the
background wifi queue.

As I have said repeatedly - clearing the bits is mandated by multiple
rfcs. Remapping is not.

Having an api to do more is out of scope for cake. Having it in cake
makes for much less interactions between other firewall rules. Try
integrating sqm-scripts with ufw, or shorewall, as examples.

I don't care enough one way or another.

If I get pissed off enough at cake I'll just fork it entirely and redo
it all my way, eventually.

**Pull request merged**
