### PR TITLE
ack_filter: protect DCTCP with stricter filtering of ECE marks

### PR DESCRIPTION
**Pull request by rmounce**
And attempt to justify our behaviour in comments.

### CODE REVIEW

**Comment by tohojo** [comment]
No, I think the safe thing here is to just not drop any packets with flags set. We really cannot assume any particular use of the flags; see e.g. RFC 8311 for other things people might be doing with those flags...

**Comment by rmounce** [comment]
I hadn't seen that ECN nonce had been marked historic, I agree that the NS should be unhandled.

On the other hand, not filtering ACKs with ECE set has a measurable impact on performance when ECN is in use, which incentivises disabling ECN altogether in order improve throughput which is disappointing. I inadvertently tested this today, the effect is pretty much the same as not filtering SACKs... (as for a single mark a stream of ACKs is sent with ECE set for one RTT interval, rather than the same for a loss except with the SACK option).

I've updated the patch to mark ACKs with NS set as ineligible, and to extend the ECE flag check to also apply to CWR as there's little cost associated with gaining safety here.

In the meantime I have only skimmed RFC 8311 and will find some time later to read it properly, but it only appears to be re-opening the IP ECT(1) codepoint after the completion of the ECN nonce experiment. There is no mention of changing the meaning of the TCP ECE/CWR flags as we are handling them here. DCTCP is still the only proposal I have seen to modify the way ECE is used, and we are now safe with that (even though DCTCP itself is not considered safe for use on the wider internet).

**Comment by tohojo** [comment]
Shouldn't we be checking that the flags are the same as the packet being enqueued, then, rather than checking against other packets already in the queue? In aggressive mode the check is meaningless, otherwise...

**Comment by rmounce** [comment]
Generally no as we should preserve each rising or falling ‘edge’. If comparing to the triggering ACK, the value of ECE could change after the first eligible ACK, and then back again for the triggering packet resulting in a loss of information for DCTCP.

I considered adding a special case for aggressive mode, but I’d sooner remove aggressive mode than expending effort to make it perfectly RFC-safe. It can improve throughput in some specific cases as well as having lower CPU overhead so personally I’d leave it as is with a clear “do not use unless you accept the consequences” warning. The way in which I would extend the extra safe ECE flag check to aggressive mode would see it lose the CPU advantage.

**Comment by tohojo** [comment]
But if we are checking all eligible packets for equality with the enqueued packet, we are also implicitly checking them for equality with each other?

**Comment by rmounce** [comment]
Consider the sequence
(already sent) ECE 0
A ECE 1
B ECE 0
C ECE 1 (triggering)

If we check that there is no change between A and the triggering packet C, we could naively decide to filter A and lose information for an ECE event.

The packet that may be filtered needs to have the same ECE value as the next eligible ACK, in order to avoid filtering some information for DCTCP.

**Comment by tohojo** [comment]
Ryan Mounce <notifications@github.com> writes:

> Consider the sequence
> (already sent) ECE 0
> A ECE 1
> B ECE 0
> C ECE 1 (triggering)
>
> If we check that there is no change between A and the triggering
> packet C, we could naively decide to filter A and lose information for
> an ECE event.
>
> The packet that may be filtered needs to have the same ECE value as
> the next eligible ACK, in order to avoid filtering some information
> for DCTCP.

Ah, sorry, I misunderstood what your patch was doing. But shouldn't we
*also* be checking that the flag value is the same as the enqueued packet?

**Comment by rmounce** [comment]
Nope, ECE could alternate value any number of times between the first and second eligible ACKs near the head, and the triggering ACK at the tail. They’re not cumulative, so filtering can only be done by considering adjacent packets.

**Comment by tohojo** [comment]
Ryan Mounce <notifications@github.com> writes:

> Nope, ECE could alternate value any number of times between the first
> and second eligible ACKs near the head, and the triggering ACK at the
> tail. They’re not cumulative, so filtering can only be done by
> considering adjacent packets.

But if we're filtering there will only be one or two such eligible ACKs?
Every other check we do is between the enqueued packet and the ones
already in the queue, it seems odd that this differs for flags.

Also, what about ACKs that are non-eligible for other reasons?

If, in your A B C example from before, B has data segments, we will end
up filtering A, no?

Since the common case is that the bits only shift once every N packets
(for N >> 2), maybe the safe thing to do is just abort the loop entirely
if we encounter two packets with differing values?

**Comment by tohojo** [comment]
Toke Høiland-Jørgensen <toke@toke.dk> writes:

> Ryan Mounce <notifications@github.com> writes:
>
>> Nope, ECE could alternate value any number of times between the first
>> and second eligible ACKs near the head, and the triggering ACK at the
>> tail. They’re not cumulative, so filtering can only be done by
>> considering adjacent packets.
>
> But if we're filtering there will only be one or two such eligible ACKs?
> Every other check we do is between the enqueued packet and the ones
> already in the queue, it seems odd that this differs for flags.
>
> Also, what about ACKs that are non-eligible for other reasons?
>
> If, in your A B C example from before, B has data segments, we will end
> up filtering A, no?
>
> Since the common case is that the bits only shift once every N packets
> (for N >> 2), maybe the safe thing to do is just abort the loop entirely
> if we encounter two packets with differing values?

I merged something now that I think handles all the above cases,
including aggressive mode...

**Pull request merged**
