### PR TITLE
sch_cake: 2nd refactor dst/src host hash allocation flags

### PR DESCRIPTION
**Pull request by ldir-EDB0**
This is more in line with Jonathan's original intention.  Retain individual dst/src allocation flags and set based on whether we're using dual_host_src/dst (or triple isolate for both)

Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by brettowe** [comment]
looks like this broke the build

make -C /lib/modules/4.14.1-2-ARCH/build SUBDIRS=/root/sch_cake modules LDFLAGS_MODULE="--build-id=0x8d131c7533065dc08c676144b38207658cf215ad" CFLAGS_MODULE="-DCAKE_VERSION=\\\"8d131c7533065dc08c676144b38207658cf215ad\\\""
make[1]: Entering directory '/usr/lib/modules/4.14.1-2-ARCH/build'
  CC [M]  /root/sch_cake/sch_cake.o
/root/sch_cake/sch_cake.c: In function ‘cake_hash’:
/root/sch_cake/sch_cake.c:810:7: error: ‘allocate_host’ undeclared (first use in this function); did you mean ‘allocate_dst’?
   if (allocate_host) {
       ^~~~~~~~~~~~~
       allocate_dst
/root/sch_cake/sch_cake.c:810:7: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:321: /root/sch_cake/sch_cake.o] Error 1
make[1]: *** [Makefile:1503: _module_/root/sch_cake] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.14.1-2-ARCH/build'
make: *** [Makefile:8: default] Error 2

**Review by dtaht — COMMENTED** [review]
you can do this with a !!(whatever & whatever) instead, I think.

**Comment by dtaht** [comment]
I pulled #74 to fix this, but it could be shorter, as per above.

**Comment by chromi** [comment]
No, !! only converts a nonzero value to 1, it doesn't handle making sure
that all bits of a multibit mask are actually set.

Along the same lines, though, !(~x & mask) might work.

- Jonathan Morton

**Comment by xnoreq** [comment]
`a & b` returns the result of a bitwise AND on both a and b. So if you have any bits set common in a and b then you'll get those bits and only those bits also set in the result.
C has no real boolean data type (let's ignore C99's _Bool for now). Boolean expressions return the integral value 0 for false and 1 for true. Negating any non-zero expression will result in 0 aka "false", negating it again or negating 0 will result in 1 aka "true".

`!(a & b)` is therefore equivalent to `!((a & b) != 0)` which simplifies to `(a & b) == 0`.
`!!(a & b)` is therefore equivalent to `((a & b) == 0) == 0` or simplified to `(a & b) != 0` and the latter is what happens e.g. in an if-statement.
`if (17) statement` runs the statement because `17 != 0` which is 1 aka "true".

C99 provides a _Bool keyword and if you include stdbool.h you can access this through the macro `bool`. It also `#define true 1` and `#define false 0`.

This boolean data type (which is actually an unsigned int with a hack imo) allows one to simply cast to _Bool or bool if defined and get 1 aka true or 0 aka false as result. For example `(bool)0.5` results in 1 because just like in the if it does a `0.5 != 0` comparison.
Contrast that with a cast to any integer. The result would be 0 due to integer truncation.

So with C99 you could simply say `(bool)(a & b)` if you wanted a boolean (1 or 0, aka true or false) result. `!!(a & b)` is simply a hack that achieves the same thing. I'd use `(a & b) != 0` instead because it communicates the intent clearest: does this expression result in any bits set?

**Pull request merged**
