### PR TITLE
Promote ingress mode to master

### PR DESCRIPTION
**Pull request by ldir-EDB0**
As described, import ingress mode from 'cobalt' branch into mainline.

I'll do the merge in a couple of days so scream now if it's a silly idea :-)

Assuming that's ok I'll then update LEDE's concept of cake & tc to support 'ingress' mode.

### CODE REVIEW

**Comment by ldir-EDB0** [comment]
nobody screamed :-)

**Comment by guidosarducci** [comment]
Oddly, they tend to scream *after* the pain and not before. ;-)

Are you planning to include "ingress" cake support for the stable lede-17.01 branch?  I'm wondering about timeline as I'm also working on some extensive updates to sqm-scripts and thinking to add matching support.

(Would appreciate if you have a look as time permits: https://github.com/tohojo/sqm-scripts/pull/58) 

Thanks!

**Comment by ldir-EDB0** [comment]
On 27/04/17 09:54, guidosarducci wrote:
> Oddly, they tend to scream /after/ the pain and not before. ;-)
He he :-)
>
> Are you planning to include "ingress" cake support for the stable
> lede-17.01 branch? I'm wondering about timeline as I'm also working on
> some extensive updates to sqm-scripts and thinking to add matching support.
I'm not 'planning' anything at the moment.  My hope is to get 'ingress 
mode' into LEDE head so the brave/fearless/self compilers can at least 
try it.  There's quite a bit of "have you tried ingress mode" being said 
at the moment and this is stage 1 of trying to make that process easier. 
  I don't know what the policy is on backporting feature enhancements 
from master to lede-17.nn.n.   Let's get it in master first and building.
>
> (Would appreciate if you have a look as time permits:
> tohojo/sqm-scripts#58 <https://github.com/tohojo/sqm-scripts/pull/58>)
I'm aware of your efforts in that area, think it's fantastic and a great 
improvement.  That said I've not actually tried any of it due to lack of 
time.  That may change next week but....life often 'happens' :-)

**Comment by moeller0** [comment]
Okay, it seems rather obvious that sqm-scripts will need to work with a bunch of cake modules with different capabilities. I believe this makes on-line testing whether capabilities are available quite important. Not that I have much time, but this now is my main priority for sqm-scripts....

**Comment by Lochnair** [comment]
@kdarbyshirebryant Did someone scream?

**Comment by ldir-EDB0** [comment]
Sort of - someone posted on IRC that they thought egress control had got poorer, also coincidentally I saw poor latency under load results last night during a network backup.... so I've taken the safest option and reverted.  JM is the expert here and I suspect there's some subtlety I've missed.

**Pull request merged**
