### PR TITLE
Makefile fix - multi file modules

### PR DESCRIPTION
**Pull request by ldir-EDB0**
This is probably what you're looking for when building modules from >1 source file.

That's what this book tells me at least, and it appears to work :-)

### CODE REVIEW

**Comment by chromi** [comment]
> On 5 Jun, 2016, at 01:37, Kevin Darbyshire-Bryant notifications@github.com wrote:
> 
> This is probably what you're looking for when building modules from >1 source file.
> 
> That's what this book tells me at least, and it appears to work :-)

For me, an equivalent construct builds and inserts, but double-faults as soon as I attach it to an interface - even one with no traffic.

Any ideas?
- Jonathan Morton

**Comment by ldir-EDB0** [comment]
I should have been clearer in my 'and it appears to work' comment.  I meant it appears to compile and build the full module.  Without this change only the kernel 'module' code got built, so it did nothing.  A check on file sizes proved the module was being built without the actual cake functionality, so some research in the 'linux device drivers' book showed how to build a module using more than one source file.  With that done, file size was much closer to that expected and I could see sch_cake.c actually being compiled.

In terms of actual module functionality...it installs but like you as soon as it's instantiated on an interface my test router goes for a lunch break ;-)  I've not had any time to investigate beyond that, sorry.

**Comment by chromi** [comment]
> On 12 Jun, 2016, at 12:06, Kevin Darbyshire-Bryant notifications@github.com wrote:
> 
> In terms of actual module functionality...it installs but like you as soon as it's instantiated on an interface my test router goes for a lunch break ;-) I've not had any time to investigate beyond that, sorry.

I see.  Well, in the interests of getting the damned thing to work, I think I’ll just move (or #include) the COBALT code into sch_cake.c and retain the old build method.  There’s obviously something we’ve both missed, but I really don’t feel like trying to troubleshoot that simultaneously with trying out the new AQM.
- Jonathan Morton

**Comment by chromi** [comment]
> On 12 Jun, 2016, at 16:00, Jonathan Morton chromatix99@gmail.com wrote:
> 
> > On 12 Jun, 2016, at 12:06, Kevin Darbyshire-Bryant notifications@github.com wrote:
> > 
> > In terms of actual module functionality...it installs but like you as soon as it's instantiated on an interface my test router goes for a lunch break ;-) I've not had any time to investigate beyond that, sorry.
> 
> I see.  Well, in the interests of getting the damned thing to work, I think I’ll just move (or #include) the COBALT code into sch_cake.c and retain the old build method.  There’s obviously something we’ve both missed, but I really don’t feel like trying to troubleshoot that simultaneously with trying out the new AQM.

Hum.  Having just actually tried that, it’s still double-faulting when I bring it up.  It appears the trouble lies elsewhere than the build method.

I suppose I’d better go over the code with a fine-toothed comb.
- Jonathan Morton

**Pull request closed without merging**
