### PR TITLE
Permit use of connmarks as tin classifiers

### PR DESCRIPTION
**Pull request by ldir-EDB0**
Add flag 'FWMARK' to enable use of firewall connmarks as tin selector.
The connmark (skbuff->mark) needs to be in the range 1<->tin_cnt ie. for
diffserv 3 the mark needs to be 1<->3

Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by tohojo** [comment]
Could you expand the commit message a bit with an explanation for *why* using
fwmark is useful, please? I'm planning to re-use your commit message for the
upstream submission, and having that in there is useful :)

**Comment by ldir-EDB0** [comment]
Sure, once I've got rid of my blinding headache - uurggh

**Comment by ldir-EDB0** [comment]
Have updated the commit message - no idea if coherent!

**Comment by tohojo** [comment]
Great, thanks!

**Pull request merged**
